//: Playground - noun: a place where people can play

/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

let maxValue = 4_000_000

func sumEvenFibonacci() -> Int {
    var sum = 0
    var n1 = 0
    var n2 = 1
    var current = 0
    
    while current < maxValue {
        current = n1 + n2
        if current % 2 == 0 {
            sum += current
        }
        n1 = n2
        n2 = current
    }
    
    
    return sum
}

print(sumEvenFibonacci())

